name: Docker Image12

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        language: [ 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  build:
  
    name: Build Docker Image Locally
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image (for testing only)
        run: docker build . --file Dockerfile --tag hello-world-py:local

  docker:
    needs: build
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/hello-world-py:latest
  deploy:
    needs: docker
    name: Through EC2
    runs-on: ubuntu-latest
      steps:
      - name: Deploy Docker image on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_HOSTNAME }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ vars.DOCKER_USERNAME }}/hello-world-py:latest
            docker stop ${{ vars.DOCKER_USERNAME }}/hello-world-py:latest
            docker rm ${{ vars.DOCKER_USERNAME }}/hello-world-py:latest
            docker run -d -p 80:5000 ${{ vars.DOCKER_USERNAME }}/hello-world-py:latest