name: Docker Image12

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- CodeQL Analysis Job ---
  test:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        language: [ 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # --- Docker Build Job (local test only) ---
  build:
    name: Build Docker Image Locally
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image (for testing only)
        run: docker build . --file Dockerfile --tag hello-world-py:${{ github.sha }}

  # --- Docker Hub Push Job ---
  docker:
    needs: build
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/hello-world-py:${{ github.sha }}

  # --- EC2 Deployment Job ---
  deploy:
    needs: docker
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy Docker image on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_HOSTNAME }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker pull ${{ vars.DOCKER_USERNAME }}/hello-world-py:${{ github.sha }}
            sudo docker stop ${{ vars.DOCKER_USERNAME }}/hello-world-py || true
            sudo docker rm ${{ vars.DOCKER_USERNAME }}/hello-world-py || true
            sudo docker run -d --name hello-world -p 80:5000 ${{ vars.DOCKER_USERNAME }}/hello-world-py:${{ github.sha }}
